spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/uniform?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:true
server:
  port: 8181
